class PhysiotheraphyMovements {
  List<Map> movements = [
    // A
    {
      "Abducting the thumb to a target": "",
      "Active aasisted knee flexion and extension": "",
      "Active cycle for upper limbs": "",
      "Ankle dorsiflexion using ribbon on toes": "",
      "Ankle dorsiflexion while sitting": "",
      "Ankle dorsiflexor electrical stimulation": "",
      "Ankle dorsiflexor strengthening in sitting using sandbag weights": "",
      "Ankle dorsiflexor strengthening in long sitting": "",
      "Ankle dorsiflexor strengthening in sitting without weights": "",
      "Ankle dorsiflexor strengthening in standing by kicking a ball backwards":
          "",
      "Ankle dorsiflexorplantarflexor strengthening in sidelying without weights":
          "",
      "Ankle dorsiflexorplantarflexor strengthening in sitting by drawing circles with the foot":
          "",
      "Ankle evartor strengthening in sitting with assistance": "",
      "Ankle invertorevertor strengthening in sitting without weights": "",
      "Ankle plantarflexor strengthening in sitting using sandbag weights": "",
      "Ankle plantarflexor strengthening in sitting using theraband": "",
      "Ankle plantarflexor strengthening in sitting without weights": "",
      "Ankle plantarflexor strengthening in standing using a wedge": "",
      "Ankle plantarflexor strengthening in supine using theraband": "",
      "Ankle plantarflexor strengthening off a wedge": "",
      "Ankle plantarflexor stretch by walking up a steep slope": "",
      "Ankle plantarflexor stretch using a foam block": "",
      "Ankle plantarflexor stretch using a sustained torque device": "",
      "Anterior deltoid electrical stimulation": "",
      "Ascending a kerb using a pole": "",
      "Ascending a step using a doorway": "",
      "Ascending kerb forwards in a wheelchair": "",
      "Assisted ankle plantarflexor stretch": "",
      "Assisted bilateral ankle stretch on a wedge": "",
      "Assisted bilateral hamstring stretch in supine": "",
      "Assisted commando crawl": "",
      "Assisted cough in sitting using a mechanical in-exsufflator": "",
      "Assisted cough in supine with one person assist - double forearm hold":
          "",
      "Assisted cough in supine with one person assist - hand and forearm hold":
          "",
      "Assisted crawling": "",
      "Assisted gastrocnemius stretch in supine": "",
      "Assisted hip adductor stretch sitting on an adult's lap": "",
      "Assisted hip adductor stretch sitting on the floor": "",
      "Assisted moving between crawling and sitting": "",
      "Assisted prone": "",
      "Assisted sit to stand from a block": "",
      "Assisted soleus stretch in supine": "",
      "Assisted standing at a table": "",
      "Assisted standing between carer's legs": "",
      "Assisted unilateral ankle stretch on wedge": "",
      "Assisted unilateral hamstring stretch in supine": "",
      "Assisted walking pushing a pram": "",
      "Attaining a wheelstand": "",
    },
    // B
    {},
    //C
    {
      "Carry astride the hip": "",
      "Carry astride the hip facing out": "",
      "Cat stretch": "",
      "Changing wheels in wheelchair": "",
      "Climbing into and out of a box": "",
      "Climbing off a lounge": "",
      "Climbing on playground equipment": "",
      "Climbing onto a lounge": "",
      "Climbing sideways on playground equipment": "",
      "Commando crawl through a tunnel": "",
      "Commando crawling": "",
      "Connecting a plug and socket": "",
      "Controlling finger flexor force by lowering peg from horizontal to vertical":
          "",
      "Controlling grip force by lifting a sealed bottle and straw": "",
      "Crab-walking": "",
      "Crawling": "",
      "Crawling backwards down a single step": "",
      "Crawling down stairs backwards": "",
      "Crawling onto a cushion": "",
      "Crawling through a tunnel": "",
      "Crawling through playground equipment": "",
      "Crawling up a slope": "",
      "Crawling up a step": "",
      "Crawling up stairs": "",
      "Cross-legged sitting": "",
      "Cruising along furniture": "",
      "Cruising around a corner": "",
      "Cupping the hand on a table": "",
      "Cupping the hand while picking up a plate": "",
      "Cutting with a knife": "",
    },
    // D *
    {
      "Depressing a fork using the fingertips": "",
      "Depressing a fork whilst holding onto tweezers and a coin": "",
      "Descending grassy slope in a wheelchair": "",
      "Descending kerb forwards in a wheelchair": "",
      "Descending slope forwards in a wheelchair": "",
      "Descending stairs backwards in a wheelchair": "",
      "Descending stairs forwards in a wheelchair": "",
    },
    // E
    {},
    // F *
    {
      "Finger and thumb extansor strengthening using an elastic band": "",
      "Finger and thumb flexor strengthening using foam": "",
      "Finger and thumb flexor strengthening using grip device": "",
      "Finger and wrist flexor strech": "",
      "Finger and wrist flexor strech in sitting by weight-bearing throughs hands":
          "",
      "Finger extansor electrical stimulation": "",
      "Finger extansor strengthening in sitting without weights": "",
      "Finger flexor and intrinsic muscle strengthening": "",
      "Flexing the hips in sitting and sliding arms forward on a table to a target":
          "",
      "Forearm pronation and supination in sitting": "",
      "Forearm pronator strech in sitting": "",
      "Forearm supination": "",
      "Forearm supination and pronation to a wall target": "",
      "Forearm supinator strech in sitting": "",
    },
    // G
    {},
    // H
    {
      "Hip extensor and flexor strengthening in sidelying using a skateboard":
          "",
      "Hip extensor and flexor strengthening in sidelying using a slideboard":
          "",
      "Hip extensor and flexor strengthening in sidelying using slings and targets":
          "",
      "Hip extensor strengthening in prone using pulleys": "",
      "Hip extensor strengthening in prone using theraband": "",
      "Hip extensor strengthening in prone using weights": "",
      "Hip extensor strengthening in prone without weights": "",
      "Hip extensor strengthening in standing": "",
      "Hip extensor strengthening in standing using sandbag weights": "",
      "Hip extensor stretch in supine": "",
      "Hip extensorflexor strengthening in sidelying using a slideboard": "",
      "Hip extensorflexor strengthening in sidelying without weights": "",
      "Hip external rotator and abductor stretch in long sitting": "",
      "Hip external rotator and abductor stretch in supine": "",
      "Hip external rotator strengthening in sidelying without weights": "",
      "Hip external rotator strengthening in sitting using pulleys": "",
      "Hip external rotator strengthening in sitting using theraband": "",
      "Hip external rotator strengthening in sitting using weights": "",
      "Hip external rotator strengthening in sitting without weights": "",
      "Hip external rotator stretch in sitting": "",
      "Hip flexor strengthening - lifting the foot while keeping the knee bent":
          "",
      "Hip flexor strengthening in sidelying using a slideboard and theraband":
          "",
      "Hip flexor strengthening in sitting": "",
      "Hip flexor strengthening in sitting using a ball as a cue": "",
      "Hip flexor strengthening in sitting using scales": "",
      "Hip flexor strengthening in sitting using weights": "",
      "Hip flexor strengthening in standing using pulleys": "",
      "Hip flexor strengthening in standing using theraband": "",
      "Hip flexor strengthening in standing using weights": "",
      "Hip flexor strengthening in supine": "",
      "Hip flexor strengthening in supine using pulleys": "",
      "Hip flexor strengthening in supine using theraband": "",
      "Hip flexor strengthening in supine using weights": "",
      "Hip flexor stretch in half-kneeling": "",
      "Hip flexor stretch in prone": "",
      "Hip flexor stretch in prone through lifting up onto elbows": "",
      "Hip flexor stretch in supine": "",
      "Hip flexor stretch in supine by holding onto knee": "",
      "Hip flexor stretch in supine over edge of plinth": "",
      "Hip flexor stretch on a wedge": "",
      "Hip internal rotator strengthening in lying using slings": "",
      "Hip internal rotator strengthening in sitting using pulleys": "",
      "Hip internal rotator strengthening in sitting using theraband": "",
      "Hip internal rotator strengthening in sitting using weights": "",
      "Hip internal rotator strengthening in supine using a stool": "",
      "Hip internal rotator stretch in long sitting": "",
      "Hip internal rotator stretch in sitting": "",
      "Hopping forward": "",
      "Hopping forwards over lines": "",
      "Hopping in different directions": "",
      "Hopping on the spot": "",
      "Hyolaryngeal excursion (Mendelsohn manoeuvre)": "",
    },
    // I
    {},
    // J
    {},
    // K
    {
      "Kicking a ball": "",
      "Knee control in standing": "",
      "Knee extension in standing": "",
      "Knee extensor and flexor strengthening in sidelying using slings and targets":
          "",
      "Knee extensor electrical stimulation": "",
      "Knee extensor strengthening at end of range using theraband": "",
      "Knee extensor strengthening in long sitting using biofeedback": "",
      "Knee extensor strengthening in sitting using theraband": "",
      "Knee extensor strengthening in sitting using weights": "",
      "Knee extensor strengthening in sitting without weights": "",
      "Knee extensor strengthening using device": "",
      "Knee flexor and extensor strengthening in sitting using a skateboard":
          "",
      "Knee flexor electrical stimulation": "",
      "Knee flexor strengthening in prone using pulleys": "",
      "Knee flexor strengthening in prone using theraband": "",
      "Knee flexor strengthening in prone using weights": "",
      "Knee flexor strengthening in sitting using theraband": "",
      "Knee flexor strengthening in standing using pulleys": "",
      "Knee flexor strengthening in standing using theraband": "",
      "Knee flexor strengthening in standing using weights": "",
      "Knee flexor strengthening in supine using skateboard": "",
      "Knee flexor strengthening in supported standing without weights": "",
      "Knee flexor strengthening in unsupported standing without weights": "",
      "Knee flexor strengthening over the edge of a bed using theraband": "",
      "Knee flexorextensor strengthening in sidelying using slideboard": "",
      "Kneeling over a carer's leg": "",
    },
    // L *
    {
      "Lifting in wheelchair": "",
      "Lifting in sort sitting with a second plinth in front": "",
      "Lifting parallel bars in standing": "",
      "Lifting parallel bars from a seated position": "",
      "Lifting in long sitting using scales": "",
      "Lifting in long sitting using blocks": "",
      "Lifting in long sitting by rotating the trunk": "",
      "Lifting an object from te floor to the table": "",
      "Leaping sideways": "",
      "Leaping off a mini-trampoline": "",
      "Leaping off a block": "",
      "Leaping from a standing start and landing on one leg": "",
      "Leaping from a standing start and landing on both legs": "",
      "Leaning to the side in sitting": "",
      "Leaning forwards on a large ball in kneeling": "",
    },
    // M
    {},
    // N
    {},
    // O
    {},
    // P
    {
      "Passive ankle movements": "",
      "Passive elbow movements": "",
      "Passive finger and hand movements": "",
      "Passive hip and knee movements": "",
      "Passive shoulder abduction": "",
      "Passive shoulder flexion": "",
      "Passive wrist flexion and extension": "",
      "Passive wrist pronation and supination": "",
      "Passiveactive cycle for upper andor lower limbs": "",
      "Pectoralis electrical stimulation": "",
      "Pectoralis stretch against a doorway": "",
      "Pectoralis stretch in standing": "",
      "Pharyngeal strengthening (effortful swallow)": "",
      "Picking an object off the floor": "",
      "Picking up a coin": "",
      "Picking up an object between the thumb and fingertips": "",
      "Picking up and holding onto coins": "",
      "Picking up coins and placing them in a jar": "",
      "Picking up objects with the toes": "",
      "Pincer grip strengthening": "",
      "Piriformis stretch": "",
      "Pivoting in prone": "",
      "Pivoting in sitting": "",
      "Placing in side sitting": "",
      "Placing in sidelying": "",
      "Placing pegs in a peg board": "",
      "Play in assisted standing": "",
      "Play in kneeling": "",
      "Play in supine": "",
      "Playing with feet with assistance": "",
      "Playing with one foot with assistance": "",
      "Popping bubble wrap between the fingers": "",
      "Posterior deltoid electrical stimulation": "",
      "Posterior deltoid stretch in sitting": "",
      "Posterior shoulder stretch": "",
      "Pouring beans from a cup": "",
      "Pouring beans into a cup": "",
      "Pouring water between cups": "",
      "Pouring water from one cup to another": "",
      "Pouring water into a cupped palm": "",
      "Pressing numbers on a phone": "",
      "Prone carry": "",
      "Prone carry along the arm": "",
      "Prone carry over both arms": "",
      "Prone lying on a carer's lap": "",
    },
    // R
    {},
    // S *
    {
      "Seated push-up": "",
      "Seated walking": "",
      "Shifting a pen up and down within the band (Caterpillar)": "",
      "Shoulder abductor and adductor strengthening in supine using slings": "",
      "Shoulder abductor strengthening in sitting using free weights": "",
      "Shoulder abductor strengthening in sitting using pulleys": "",
      "Shoulder abductor strengthening in sitting using theraband": "",
      "Shoulder abductor strengthening in standing using theraband": "",
      "Shoulder abductor strengthening in supine using theraband": "",
      "Shoulder abductor strengthening using Uppertone": "",
      "Shoulder abductoradductor strengthening in supine using free weights":
          "",
      "Shoulder adductor and forearm pronator stretch in sitting": "",
      "Shoulder adductor and forearm supinator stretch in sitting": "",
      "Shoulder adductor stretch in sitting": "",
      "Shoulder and trunk strengthening by maintaining a plank position": "",
      "Shoulder depression with arm in abduction": "",
      "Shoulder depressor strengthening in sitting using slings": "",
      "Shoulder depressor strengthening in sitting using Uppretone": "",
      "Shoulder extensor and forearm pronator stretch": "",
      "Shoulder extensor and forearm supinator stretch": "",
      "Shoulder extensor strengthening in sitting using free weights": "",
      "Shoulder extensor strengthening in sitting using pulleys": "",
      "Shoulder extensor strengthening in sitting using theraband": "",
      "Shoulder extensor strengthening in sitting using Uppertone": "",
      "Shoulder extensor strengthening in standing using theraband": "",
      "Shoulder extensor strengthening in supine using theraband": "",
      "Shoulder extensorflexor strengthening in prone using free weights": "",
      "Shoulder external rotator strengthening in prone using free weights": "",
      "Shoulder external rotator strengthening in sidelying using free weights":
          "",
      "Shoulder external rotator strengthening in sitting using free weights":
          "",
      "Shoulder external rotator strengthening in sitting using free weights with arm supported":
          "",
      "Shoulder external rotator strengthening in sitting using pulleys": "",
      "Shoulder external rotator strengthening in sitting using theraband": "",
      "Shoulder external rotator strengthening in sitting using Uppertone": "",
      "Shoulder external rotator strengthening in standing using theraband": "",
      "Shoulder external rotator strengthening in supine using free weights":
          "",
      "Shoulder external rotator strengthening in supine using theraband": "",
      "Shoulder externalinternal rotator strengthening in supine using springs":
          "",
      "Shoulder flexor strengthening in sitting using free weights": "",
    },
    // T
    {},
    // U
    {},
    // W *
    {
      "Walking a set distance within a set time":
          "Walking a set distance within a set time.jpg",
      "Walking along a low wall": "Walking along a low wall.jpg",
      "Walking and dribbling a ball around obstacles":
          "Walking and dribbling a ball around obstacles.jpg",
      "Walking backwards": "Walking backwards.jpg",
      "Walking backwards along a line": "Walking backwards along a line.jpg",
      "Walking backwards pulling a toy": "Walking backwards pulling a toy.jpg",
      "Walking between a carer and furniture":
          "Walking between a carer and furniture.jpg",
      "Walking between furniture": "Walking between furniture.jpg",
      "Walking between lines": "Walking between lines.jpg",
      "Walking between two people": "Walking between two people.jpg",
      "Walking down stairs": "Walking down stairs.jpg",
      "Walking down stair": "Walking down stair.jpg",
      "Walking down stairs using a hand rail":
          "Walking down stairs using a hand rail.jpg",
      "Walking down stairs with assistance":
          "Walking down stairs with assistance.jpg",
      "Walking forwards over lines": "Walking forwards over lines.jpg",
      "Walking hands forward and backward while prone on a ball":
          "Walking hands forward and backward while prone on a ball.jpg",
      "Walking in a figure-of-eight": "Walking in a figure-of-eight.jpg",
      "Walking in a harness": "Walking in a harness.jpg",
      "Walking in a harness to targets": "Walking in a harness to targets.jpg",
      "Walking lunge": "Walking lunge.jpg",
      "Walking on a balance beam": "Walking on a balance beam.jpg",
      "Walking on a balance beam with assistance":
          "Walking on a balance beam with assistance.jpg",
      "Walking on a line": "Walking on a line.jpg",
      "Walking on a line while bouncing a ball":
          "Walking on a line while bouncing a ball.jpg",
      "Walking on a treadmill in a harness with assistance":
          "Walking on a treadmill in a harness with assistance.jpg",
      "Walking on a treadmill in a harness with pillowcase to assist swing":
          "Walking on a treadmill in a harness with pillowcase to assist swing.jpg",
      "Walking on a treadmill in a harness with theraband to assist swing":
          "Walking on a treadmill in a harness with theraband to assist swing.jpg",
      "Walking on an unstable surface using playground equipment":
          "Walking on an unstable surface using playground equipment.jpg",
      "Walking on heels": "Walking on heels.jpg"
    },
  ];
}
