// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfjhh5IjqG2ES8SmAMgqXWCUynLnImsnA',
    appId: '1:345236344555:web:8594673f482b19a471b8ae',
    messagingSenderId: '345236344555',
    projectId: 'fittech-90d09',
    authDomain: 'fittech-90d09.firebaseapp.com',
    storageBucket: 'fittech-90d09.appspot.com',
    measurementId: 'G-40VK70B7Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDikscVXB56rRBPxMWFLzTaXgM0__F8drY',
    appId: '1:345236344555:android:9d7da5ddb4a512c571b8ae',
    messagingSenderId: '345236344555',
    projectId: 'fittech-90d09',
    storageBucket: 'fittech-90d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FyCZF9baJ5AqaH_qWoGSfu_miO0_w3k',
    appId: '1:345236344555:ios:3f4d2d2f8a1ed7b471b8ae',
    messagingSenderId: '345236344555',
    projectId: 'fittech-90d09',
    storageBucket: 'fittech-90d09.appspot.com',
    iosClientId: '345236344555-g70rsejtnspfbicqafq0j49277cpvqgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FyCZF9baJ5AqaH_qWoGSfu_miO0_w3k',
    appId: '1:345236344555:ios:e778c1841e8096ab71b8ae',
    messagingSenderId: '345236344555',
    projectId: 'fittech-90d09',
    storageBucket: 'fittech-90d09.appspot.com',
    iosClientId: '345236344555-fe1n46banhpqj150jj0prel98cnfus56.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker.RunnerTests',
  );
}
