class PhysioteraphyMovements{
  List<Map> movements = [
    {//pictures finded ve assets added
    "Balancing on a ball":"assets/B harfi/balancing_on_ball.png",
    "Balancing on a ball while lifting one leg up and down":"assets/B harfi/Balancing on a ball while lifting one leg up and down.png",
    "Balancing while sitting on a moving object":"assets/B harfi/Balancing while sitting on a moving object.png",
    "Bear walking":"assets/B harfi/bear walking.png",
    "Bear-walking up a slope with assistance":"assets/B harfi/Bear-walking up a slope with assistance.png",
    "Bench press":"assets/B harfi/bench-press.png",
    "Bending and straightening the wrist to targets":"assets/B harfi/Bending and straightening the wrist to targets.png",
    "Bending the knee in sitting":"assets/B harfi/Bending the knee in sitting.png",
    "Bending the knee in sitting using a roller-skate":"assets/B harfi/Bending the knee in sitting using a roller-skate.png",
    "Bending the wrist to a target":"assets/B harfi/Bending the wrist to a target.png",
    "Bending the wrist while holding a cup":"assets/B harfi/Bending the wrist while holding a cup.png",
    "Biceps electrical stimulation":"assets/B harfi/Biceps electrical stimulation.png",
    "Bilateral ankle plantarflexor stretch using a wedge while standing against wall":"assets/B harfi/Bilateral ankle plantarflexor stretch using a wedge while standing against wall.png",
    "Bilateral ankle plantarflexor stretch using a wedge while standing at a table":"assets/B harfi/Bilateral ankle plantarflexor stretch using a wedge while standing at a table.png",
    "Bilateral calf raises":"assets/B harfi/Bilateral calf raises.png",
    "Bilateral calf raises on a block":"assets/B harfi/Bilateral calf raises on a block.png",
    "Bilateral shoulder adductor stretch in supine (crucifix)":"assets/B harfi/Bilateral shoulder adductor stretch in supine (crucifix).png",
    "Bilateral shoulder internal rotator stretch in supine":"assets/B harfi/Bilateral shoulder internal rotator stretch in supine.png",
    "Bilateral shoulder stretch in supine":"assets/B harfi/Bilateral shoulder stretch in supine.png",
    "Bilateral squat in standing":"assets/B harfi/Bilateral squat in standing.png",
    "Bilateral squat on tilt table":"assets/B harfi/Bilateral squat on tilt table.png",
    "Bilateral squat to a target in standing":"assets/B harfi/Bilateral squat to a target in standing.png",
    "Bimanual table top task using a toy":"assets/B harfi/imanual table top task using a toy.png",
    "Bouncing a ball with one hand":"assets/B harfi/Bouncing_a_ball_with_one_hand.png",
    "Boxing in a wheelchair":"assets/B harfi/Boxing_in_a_wheelchair.png",
    "Boxing in sitting":"assets/B harfi/Boxing in sitting.png",
    "Braiding":"assets/B harfi/Braiding.png",
    "Bridging":"assets/B harfi/Bridging.png",
    "Bridging gaps between furniture":"assets/B harfi/Bridging gaps between furniture.png",
    "Bridging on a large ball":"assets/B harfi/Bridging on a large ball.png",
    "Bridging while rolling ball under the body":"assets/B harfi/vBridging while rolling a ball under the body.png",
    "Bringing the wheelchair to an upright position":"assets/B harfi/Bringing the wheelchair to an upright position.png",
    },

    {//pictures finded ve assets added
      "Elbow extensor strengthening in lying without weights":"assets/E harfi/Elbow extensor strengthening in lying without weights.png",
      "Elbow extensor strengthening in prone using free weights":"assets/E harfi/Elbow extensor strengthening in prone using free weights.png", 
      "Elbow extensor strengthening in sitting using free weights":"assets/E harfi/Elbow extensor strengthening in sitting using free weights.png",
      "Elbow extensor strengthening in sitting using pulleys":"assets/E harfi/Elbow extensor strengthening in sitting using pulleys.png",
      "Elbow extensor strengthening in sitting using theraband":"assets/E harfi/Elbow extensor strengthening in sitting using theraband.png",
      "Elbow extensor strengthening in sitting using Uppertone":"assets/E harfi/Elbow extensor strengthening in sitting using Uppertone.png",
      "Elbow extensor strengthening in supine using free weights":"assets/E harfi/Elbow extensor strengthening in supine using free weights.png", 
      "Elbow extensor strengthening in supine using theraband":"assets/E harfi/Elbow extensor strengthening in supine using theraband.png",
      "Elbow flexor strengthening in sitting using free weights":"assets/E harfi/Elbow flexor strengthening in sitting using free weights.png",
      "Elbow flexor strengthening in sitting using pulleys":"assets/E harfi/Elbow flexor strengthening in sitting using pulleys.png",
      "Elbow flexor strengthening in sitting using theraband":"assets/E harfi/Elbow flexor strengthening in sitting using theraband.png",
      "Elbow flexor stretch in supine":"assets/E harfi/Elbow flexor stretch in supine.png",
      "Elbow flexor/extensor strengthening in sidelying using slings":"assets/E harfi/Elbow flexorextensor strengthening in sidelying using slings.png",
      "Elbow flexor/extensor strengthening in sitting using slings":"assets/E harfi/Elbow flexorextensor strengthening in sitting using slings.png",
      "Elbow flexor/extensor strengthening in supine using springs":"assets/E harfi/Elbow flexorextensor strengthening in supine using springs.png",
      "Extended the arm to a target in lying":"",

      },

      {//pictures finded ve assets added
        "Gastrocnemius electrical stimulation":"assets/G harfi/Gastrocnemius electrical stimulation.png",
        "Getting onto and sliding down a slide":"assets/G harfi/Getting onto and sliding down a slide.png",
        "Getting up from the floor":"assets/G harfi/Getting up from the floor.png",
        "Gluetal electrical stimulation":"assets/G harfi/Gluteal electrical stimulation.png",
        "Going down stairs in sitting":"assets/G harfi/Going down stairs in sitting.png",
      },

      {//pictures finded ve assets added
        "Internal hip rotator strengthening in sidelying without weights":"assets/I harfi/Internal hip rotator strengthening in sidelying without weights.png",
      },

      {//pictures finded ve assets added
        "Jogging on a mini-trampoline":"assets/J harfi/Jogging on a mini-trampoline.png",
        "Jumping between hoops with feet together":"assets/J harfi/Jumping between hoops with feet together.png",
        "Jumping forwards over lines":"assets/J harfi/Jumping forwards over lines.png",
        "Jumping from a step with assistance":"assets/J harfi/Jumping from a step with assistance.png",
        "Jumping from side to side":"assets/J harfi/Jumping from side to side.png",
        "Jumping in diffrent directions":"assets/J harfi/Jumping in different directions.png",
        "Jumping off a low object":"assets/J harfi/Jumping off a low object.png",
        "Jumping off a mini-trampoline":"assets/J harfi/Jump off a mini-trampoline.png",
        "Jumping on a mini-trampoline":"assets/J harfi/Jump on a mini-trampoline.png",
        "Jumping on the spot":"assets/J harfi/Jumping on the spot.png",
      },

      {//pictures finded ve assets added
        "Maintaining a half-kneeling position":"assets/M harfi/Maintaining a half-kneeling position.png",
        "Maintaining a kneeling position":"assets/M harfi/Maintaining a kneeling position.png",
        "Maintaining grasp of a fork using tweezers and coin":"assets/M harfi/Maintaining grasp of a fork using tweezers and a coin.png",
        "Maintaining grasp using tweezers and a coin":"assets/M harfi/Maintaining grasp using tweezers and a coin.png",
        "Maintaining half-kneeling":"assets/M harfi/Maintaining half-kneeling.png",
        "Maintaining single-leg stance while kicking a ball":"assets/M harfi/Maintaining single-leg stance while kicking a ball.png",
        "Maintaining single-leg stance while lunging forwards":"assets/M harfi/Maintaining single-leg stance while lunging forwards.png",
        "Maintaining single-leg stance while moving the other foot targets in a circle":"",//bulamadım resim
        "Maintaining single-leg stance while moving the other foot targets in a semi-circle":"assets/M harfi/Maintaining single-leg stance while moving the other foot to targets in a semi-circle.png",
        "Maintaining single-leg stance while rolling a ball around an obstacle":"assets/M harfi/Maintaining single-leg stance while rolling a ball around an obstacle.png",
        "Maintaining single-leg stance while rolling the other foot on a ball":"assets/M harfi/Maintaining single-leg stance while rolling the other foot on a ball.png",
        "Maintaining single-leg stance while stepping":"assets/M harfi/Maintaining single-leg stance while stepping.png",
        "Maintaining single-leg stance while stepping backwards with the other leg":"assets/M harfi/Maintaining single-leg stance while stepping backwards with the other leg.png",
        "Maintaining single-leg stance while stepping from a block":"assets/M harfi/Maintaining single-leg stance while stepping from a block.png",
        "Maintaining single-leg stance while touching the other foot on a block":"assets/M harfi/Maintaining single-leg stance while touching the other foot on a block.png",
        "Maintaining single-leg support while stepping up and down stairs":"assets/M harfi/Maintaining single-leg support while stepping up and down stairs.png",
        "Maintaining wheelchair while seated":"assets/M harfi/Maintaining wheelchair while seated.png",
        "Manipulating toys while sitting on a chair":"assets/M harfi/Manipulating toys while sitting on a chair.png",
        "Marching on the spot":"assets/M harfi/Marching on the spot.png",
        "Middle deltoid electrical stimulation":"assets/M harfi/Middle deltoid electrical stimulation.png",
        "Moving a fork sideways to targets using the fingerpritns":"assets/M harfi/Moving a fork sideways to targets using the fingertips.png",
        "Moving across the bed":"assets/M harfi/Moving across the bed.png",
        "Moving around the bed in short sitting":"assets/M harfi/Moving around the bed in short sitting.png",
        "Moving between prone and four-point kneeling":"assets/M harfi/Moving between prone and four-point kneeling.png",
        "Moving between side-sitting and four-point kneeling":"assets/M harfi/Moving between side-sitting and four-point kneeling.png",
        "Moving between sitting and crawling with assistance":"assets/M harfi/Moving between sitting and crawling with assistance.png",
        "Moving between squatting and standing":"assets/M harfi/Moving between squatting and standing.png",
        "Moving foot backwards to a block":"assets/M harfi/Moving foot backwards to a block.png",
        "Moving forwards in the wheelchair":"assets/M harfi/Moving forwards in the wheelchair.png",
        "Moving forwards in wheelchair":"assets/M harfi/Moving forwards in wheelchair.png",
        "Moving forwards in wheelchair starting with hands behind back":"assets/M harfi/Moving forwards in wheelchair starting with hands behind back.png",
        "Moving from bear-walking to standing":"assets/M harfi/Moving from bear-walk to standing.png",
        "Moving from kneeling to half-kneeling":"assets/M harfi/Moving from kneeling to half-kneeling.png",
        "Moving from side to side in sitting":"assets/M harfi/Moving from side to side in sitting.png",
        "Moving from squatting to standing while performing a bimanual task":"assets/M harfi/Moving from squatting to standing while performing a bimanual task.png",
        "Moving from supported bear-walking to standing":"assets/M harfi/Moving from supported bear-walking to standing.png",
        "Moving from the heels to the toes in standing":"assets/M harfi/Moving from the heels to the toes in standing.png",
        "Moving into sitting":"assets/M harfi/Moving into sitting.png",
        "Moving into sitting from a semi-upright position":"assets/M harfi/Moving into sitting from a semi-upright position.png",
        "Moving into sitting with assistance":"assets/M harfi/Moving into sitting with assistance.png",
        
      },

      {//pictures finded ve assets added
        "Neck flexor/extensor stretch":"assets/N harfi/Neck flexorextensor stretch.png",
        "Neck lateral flexor strengthening in sitting":"assets/N harfi/Neck lateral flexor strengthening in sitting.png",
        "Neck lateral flexor stretch":"assets/N harfi/Neck lateral flexor stretch.png",
        "Neck protractor strengthening in sitting":"assets/N harfi/Neck protractor strengthening in sitting.png",
        "Neck retractor strengthening":"assets/N harfi/Neck retractor strengthening.png",
        "Neck rotator strengthening in sitting":"assets/N harfi/Neck rotator strengthening in sitting.png",
        "Neck rotator stretch":"assets/N harfi/Neck rotator stretch.png",
      },
      
      {//pictures finded ve assets added
        "Off-centre carry":"assets/O harfi/Off-centre carry.png",
        "Opening a combination lock":"assets/O harfi/Opening a combination lock.png",
        "Opening a container":"assets/O harfi/Opening a container.png",
        "Opening a leash clip":"assets/O harfi/Opening a leash clip.png",
      },

       {//pictures finded ve assets added
        "Quadriceps stretch in prone":"assets/Q harfi/Quadriceps stretch in prone.png",
        "Quadriceps stretch in sitting":"assets/Q harfi/Quadriceps stretch in sitting.png",
        "Quadriceps stretch in standing":"assets/Q harfi/Quadriceps stretch in standing.png",
        
      },

      {//pictures finded ve assets added
        "Raising and lowering from a block":"assets/R harfi/Raising and lowering from a block.png",
        "Raising and lowering from a block with hand support nearby":"assets/R harfi/Raising and lowering from a block with hand support nearby.png",
        "Raising the leg onto a block":"assets/R harfi/Raising the leg onto a block.png",
        "Reaching across the body while sitting":"assets/R harfi/Reaching across the body while sitting.png",
        "Reaching behind in sitting":"assets/R harfi/Reaching behind in sitting.png",
        "Reaching diagonally in sitting":"assets/R harfi/Reaching diagonally in sitting.png",
        "Reaching down and to the side from standing":"assets/R harfi/Reaching down and to the side from standing.png",
        "Reaching down in supported standing":"assets/R harfi/Reaching down in supported standing.png",
        "Reaching down while sitting on a stool":"assets/R harfi/Reaching down while sitting on a stool.png",
        "Reaching for a large object with both hands":"assets/R harfi/Reaching for a large object with both hands.png",
        "Reaching forward in sitting":"assets/R harfi/Reaching forward in sitting.png",
        "Reaching forward to an object":"assets/R harfi/Reaching forward to an object.png",
        "Reaching forward while sitting on a chair":"assets/R harfi/Reaching forward while sitting on a chair.png",
        "Reaching from a low surface to a high suraface":"assets/R harfi/Reaching from a low surface to a high surface.png",
        "Reaching from side to side in sitting":"assets/R harfi/Reaching from side to side in sitting.png",
        "Reaching from side to side in standing":"assets/R harfi/Reaching from side to side in standing.png",
        "Reaching in four-point kneeling":"assets/R harfi/Reaching in four-point kneeling.png",
        "Reaching in kneeling using one arm":"assets/R harfi/Reaching in kneeling using one arm.png",
        "Reaching in prone with assistance":"assets/R harfi/Reaching in prone with assistance.png",
        "Reaching in standing":"assets/R harfi/Reaching in standing.png",
        "Reaching in supported sitting":"assets/R harfi/Reaching in supported sitting.png",
        "Reaching to diffrent targets":"assets/R harfi/Reaching to different targets.png",
        "Reaching to the floor in wheelchair":"assets/R harfi/Reaching to the floor in wheelchair.png",
        "Reaching to the floor in wheelchair using backrest for support":"assets/R harfi/Reaching to the floor in wheelchair using backrest for support.png",
        "Reaching to the ground in standing":"assets/R harfi/Reaching to the ground in standing.png",
        "Reaching to the side in standing":"assets/R harfi/Reaching to the side in standing.png",
        "Reaching to the side in wheelchair":"assets/R harfi/Reaching to the side in wheelchair.png",
        "Reaching to the side when standing up":"assets/R harfi/Reaching to the side when standing up.png",
        "Reaching to the side while sitting":"assets/R harfi/Reaching to the side while sitting.png",
        "Reaching up and to the side in sitting":"assets/R harfi/Reaching up and to the side in sitting.png",
        "Reaching up in sitting":"assets/R harfi/Reaching up in sitting.png",
        "Reaching up in standing":"assets/R harfi/Reaching up in standing.png",
        "Reaching up while sitting on a block":"assets/R harfi/Reaching while sitting on a block.png",
      },

      {//pictures finded ve assets added
        "Taking a cup to the mouth":"assets/T harfi/Taking a cup to the mouth.png",
        "Thoracic spine and upper-chest stretch":"assets/T harfi/Thoracic spine and upper-chest stretch.png",
        "Threading macaroni":"assets/T harfi/Threading macaroni.png",
        "Throwing a ball overhead with two hands":"assets/T harfi/Throwing a ball overhead with two hands.png",
        "Throwing a ball with one hand":"assets/T harfi/Throwing a ball with one hand.png",
        "Throwing an object underarm at a target":"assets/T harfi/Throwing an object underarm at a target.png",
        "Throwing and catching a large ball with two hands":"assets/T harfi/Throwing and catching a large ball with two hands.png",
        "Thumb abduction with electrical stimulation":"assets/T harfi/Thumb abduction with electrical stimulation.png",
        "Thumb abduction: sliding the tumb on a stick with hand on top of cup":"assets/T harfi/Thumb abduction sliding the thumb on a stick with hand on top of cup.png",
        "Thumb web-space stretch in sitting":"assets/T harfi/Thumb web-space stretch in sitting.png",
        "Toe raises in standing":"assets/T harfi/Toe raises in standing.png",
        "Tongue base strengthening (Masako manoeuvre)":"assets/T harfi/Tongue base strengthening (Masako manoeuvre).png",
        "Tongue strengthening-lateral tongue movements":"assets/T harfi/Tongue strengthening - lateral tongue movements.png",
        "Tongue strengthening-moving tongue in circular motion":"assets/T harfi/Tongue strengthening - moving tongue in circular motion.png",
        "Tongue strengthening-pressing tongue into cheek":"assets/T harfi/Tongue strengthening - pressing tongue into cheek.png",
        "Tongue strengthening-pressing vertical tongue movements":"assets/T harfi/Tongue strengthening - vertical tongue movements.png",
        "Touching the thumb to each fingertip":"assets/T harfi/Touching the thumb to each fingertip.png",
        "Transferring between two  perpendicular plinths":"assets/T harfi/Transferring between two perpendicular plinths.png",
        "Transferring  between two plinths":"assets/T harfi/Transferring between two plinths.png",
        "Transferring from floor to wheelchair off a small stool using backwards approach":"assets/T harfi/Transferring from floor to wheelchair off a small stool using backwards approach.png",
        "Transferring from floor to wheelchair using backwards approach":"assets/T harfi/Transferring from floor to wheelchair using backwards approach.png",
        "Transferring from low to high plinth":"assets/T harfi/Transferring from low to high plinth.png",
        "Transferring from small to large stool":"assets/T harfi/Transferring from small to large stool.png",
        "Transferring from small to medium stool":"assets/T harfi/Transferring from small to medium stool.png",
        "Transferring from stool to wheelchair":"assets/T harfi/Transferring from stool to wheelchair.png",
        "Transferring in long sitting from bed to wheelchair":"assets/T harfi/Transferring in long sitting from bed to wheelchair.png",
        "Transferring in long sitting from wheelchair to bed":"assets/T harfi/Transferring in long sitting from wheelchair to bed.png",
        "Transferring in long sitting from wheelchair to bed from halfway":"assets/T harfi/Transferring in long sitting from wheelchair to bed from halfway.png",
        "Transferring in long sitting using a slideboard":"assets/T harfi/Transferring in long sitting using a slideboard.png",
        "Transferring in short sitting from bed to wheelchair":"assets/T harfi/Transferring in short sitting from bed to wheelchair.png", 
      },

      {//pictures finded ve assets added
        "Unilateral ankle plantarflexor strengthening with one leg on a stool":"assets/U harfi/Unilateral ankle plantarflexor strengthening with one leg on a stool.png",
        "Unilateral ankle plantarflexor stretch on wedge":"assets/U harfi/Unilateral ankle plantarflexor stretch on wedge.png",
        "Unilateral ankle plantarflexor stretch standing against a wall":"assets/U harfi/Unilateral ankle plantarflexor stretch standing against a wall.png",
        "Unilateral ankle plantarflexor stretch using a rolled-up towel":"assets/U harfi/Unilateral ankle plantarflexor stretch using a rolled-up towel.png",
        "Unilateral hamstring stretch in long sitting":"assets/U harfi/Unilateral hamstring stretch in long sitting.png",
        "Unilateral hamstring stretch in supine":"assets/U harfi/Unilateral hamstring stretch in supine.png",
        "Unilateral shoulder internal rotator stretch in supine":"assets/U harfi/Unilateral shoulder internal rotator stretch in supine.png",
        "Upper chest and abdominal stretch":"assets/U harfi/Upper chest and abdominal stretch.png",
        "Upper limb passive movements":"assets/U harfi/Upper limb passive movements.png",
        "Upper oesophageal sphincter opening (Shaker exercise)":"assets/U harfi/Upper oesophageal sphincter opening (Shaker exercise).png",
        "Upright carry looking over a carer's shoulder":"assets/U harfi/Upright carry looking over a carer's shoulder.png",
        "Using a knife and fork":"assets/U harfi/Using a knife and fork.png",
        "Using a pen":"assets/U harfi/Using a pen.png",
        "Using a safety pin":"assets/U harfi/Using_a_safety_pin.png",
        "Using a tape measure":"assets/U harfi/Using a tape measure.png",
        "Using an adjustable spanner":"",
        "Using an eggbeater":"assets/U harfi/Using an eggbeater.png",
        "Using pegs":"assets/U harfi/Using pegs.png",
        "Using scissors":"assets/U harfi/Using scissors.png",
        "Using tweezers":"assets/U harfi/Using tweezers.png",
      },

      {//pictures finded ve assets added
      "Half-kneel to stand at furniture": "assets/H harfi/Half-kneel to stand at furniture.png",
      "Half-kneel to stand with assistance": "assets/H harfi/Half-kneel to stand with assistance.png",
      "Hamstring and ankle plantarflexor stretch in sitting": "assets/H harfi/Hamstring and ankle plantarflexor stretch in sitting.png",
      "Hamstring and ankle plantarflexor stretch in sitting using belt": "assets/H harfi/Hamstring and ankle plantarflexor stretch in sitting using belt.png",
      "Hamstring and hip adductor stretch in long sitting using wrap-around splints": "assets/H harfi/Hamstring and hip adductor stretch in long sitting using wrap-around splints.png",
      "Hamstring stretch in long sitting": "assets/H harfi/Hamstring stretch in long sitting.png",
      "Hamstring stretch in lying with legs up a wall": "assets/H harfi/Hamstring stretch in lying with legs up a wall.png",
      "Hamstring stretch in sitting": "assets/H harfi/Hamstring stretch in sitting.png",
      "Hamstring stretch in sitting with weight on knee": "assets/H harfi/Hamstring stretch in sitting with weight on knee.png",
      "Hamstring stretch in standing using a wall and stool": "assets/H harfi/Hamstring stretch in standing using a wall and stool.png",
      "Hamstring stretch in supine using slings": "assets/H harfi/Hamstring stretch in supine using slings.png",
      "Hamstring stretch in supine using standardised torque": "assets/H harfi/Hamstring stretch in supine using standardised torque.png",
      "Hand stretch": "assets/H harfi/Hand stretch.png",
      "Hand stretch of the MCP joints": "assets/H harfi/Hand stretch of the MCP joints.png",
      "Hand stretch using wheelchair": "assets/H harfi/Hand stretch using wheelchair.png",
      "Hand webspace stretch": "assets/H harfi/Hand webspace stretch.png",
      "Head control in sitting on an adult's lap": "assets/H harfi/Head control in sitting on an adult's lap.png",
      "Head turning in prone": "assets/H harfi/Head turning in prone.png",
      "Head turning in supine": "assets/H harfi/Head turning in supine.png",
      "Hee/toe walking on a line": "assets/H harfi/Hee-toe walking on line.jpg",
      "Hip abductor strengthening in sidelying againts a wall": "assets/H harfi/Hip abductor strengthening in sidelying against a wall.png",
      "Hip abductor strengthening in sidelying using pulleys": "assets/H harfi/Hip abductor strengthening in sidelying using pulleys.png",
      "Hip abductor strengthening in sidelying sandbag weights": "assets/H harfi/Hip abductor strengthening in sidelying using sandbag weights.png",
      "Hip abductor strengthening in sidelying using theraband": "assets/H harfi/Hip abductor strengthening in sidelying using theraband.png",
      "Hip abductor strengthening in standing againts a wall": "assets/H harfi/Hip abductor strengthening in standing against a wall.png",
      "Hip abductor strengthening in standing using pulleys": "assets/H harfi/Hip abductor strengthening in standing using pulleys.png",
      "Hip abductor strengthening in standing using sandbag weights": "assets/H harfi/Hip abductor strengthening in standing using sandbag weights.png",
      "Hip abductor strengthening in standing using thraband": "assets/H harfi/Hip abductor strengthening in standing using theraband.png",
      "Hip abductor strengthening using slings": "assets/H harfi/Hip abductor strengthening using slings.png",
      "Hip abductor/adductor strengthening in supine without weights": "assets/H harfi/Hip abductoradductor strengthening in supine without weights.png",
      "Hip abductor/adductor strengthening using a skateboard in supine": "assets/H harfi/Hip abductoradductor strengthening using a skateboard in supine.png",
      "Hip adductor and rotator stretch in supine with assistance": "assets/H harfi/Hip adductor and rotator stretch in supine with assistance.png",
      "Hip adductor strengthening in sidelying using pulleys": "assets/H harfi/Hip adductor strengthening in sidelying using pulleys.png",
      "Hip adductor strengthening in sidelying using theraband": "assets/H harfi/Hip adductor strengthening in sidelying using theraband.png",
      "Hip adductor strengthening in standing using pulley": "assets/H harfi/Hip adductor strengthening in standing using pulleys.png",
      "Hip adductor strengthening in standing using therabands": "assets/H harfi/Hip adductor strengthening in standing using theraband.png",
      "Hip adductor stretch in sitting": "assets/H harfi/Hip adductor stretch in sitting.png",
      "Hip adductor stretch in supine using wedge": "assets/H harfi/Hip adductor stretch in supine using wedge.png",
      "Hip adductor stretch in supine using weights": "assets/H harfi/Hip adductor stretch in supine using weights.png",
      "Hip adductor stretch in supine with assistance": "assets/H harfi/Hip adductor stretch in supine with assistance.png",
      "Hip adductor stretch in unsupported sitting": "assets/H harfi/Hip adductor stretch in unsupported sitting.png",
      "Hip adductor stretch with wedge in long sitting": "assets/H harfi/Hip adductor stretch with wedge in long sitting.png",
      "Hip and back extensor strengthening using a scooterboard": "assets/H harfi/Hip and back extensor strengthening using a scooterboard.png",
      "Hip and knee extensor stretch in sitting": "assets/H harfi/Hip and knee extensor stretch in sitting.png",
      "Hip and knee extansor stretch in supine using a strap": "assets/H harfi/Hip and knee extensor stretch in supine using a strap.png",
      "Hip and knee stretch in two point kneeling": "assets/H harfi/Hip and knee stretch in two point kneeling.png",
      "Hip extension in standing against a wall": "assets/H harfi/Hip extension in standing against a wall.png"
      },

  ];
}
